name: App CI

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '20'
          distribution: 'temurin'
      - name: Checkstyle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper
          gradle-home-cache-cleanup: true
          cache-read-only: false
          arguments: checkstyleTest
          build-root-directory: app
      - name: Checkstyle Main
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper
          gradle-home-cache-cleanup: true
          cache-read-only: false
          arguments: checkstyleTest
          build-root-directory: checkstyleMain
